dataset:
  format: nx
  name: scalefree
  split:
  - 0.8
  - 0.2
  task: graph
  task_type: classification
  transductive: true
  transform: none
gnn:
  act: prelu
  agg: max
  batchnorm: true
  dim_inner: 256
  dropout: 0.0
  layer_type: generalconv
  layers_mp: 8
  layers_post_mp: 3
  layers_pre_mp: 1
  normalize_adj: false
  stage_type: skipconcat
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  type: gnn
optim:
  base_lr: 0.01
  max_epoch: 400
  optimizer: adam
out_dir: results\design_v2_grid_round2
train:
  batch_size: 32
  ckpt_period: 100
  eval_period: 20
